#!/bin/sh

set -e

if test -z "$GITHUB_API_TOKEN"
then
    echo No GitHub API token specified
    exit 1
fi

case "$TRAVIS_BRANCH"
in
*-staging) ;;
*)
    echo This script should be run from -staging branch
    exit 1
    ;;
esac

curl \
    -X PATCH \
    -H "Authorization: token ${GITHUB_API_TOKEN}" \
    -d "{\"sha\": \"${TRAVIS_COMMIT}\"}" \
    https://api.github.com/repos/"${TRAVIS_REPO_SLUG}"/git/refs/heads/"${TRAVIS_BRANCH%-staging}"
